version: 2.0

id: "telus-standard"

about:
  title: "telus-standard"
  description: Standard for TELUS Digital

contacts:
  - type: Project Owner
    name: Stephen Marie-Rhodes
    email: Stephen.Marie-Rhodes@telus.com
    github: stepmr
  - type: Tech Lead
    name: Mauricio Mercado
    email: mauricio.mercado@telus.com
    github: maumercado

references:
  - title: NPM Package
    uri: https://www.npmjs.com/package/@telus/telus-standard

environments:
  - title: Source Code
    uri: https://github.com/telus/telus-standard.git
